sudo: required
dist: bionic
env:
    - MOZ_HEADLESS=1
addons:
    chrome: stable
    firefox: latest
language: node_js
node_js:
    - 10
    - 12 # LTS
before_install:
    - yarn global add greenkeeper-lockfile@1
before_script:
    - greenkeeper-lockfile-update
    - export DISPLAY=:99.0
services:
    - xvfb
after_script: greenkeeper-lockfile-upload
cache:
    yarn: true
    directories:
        - node_modules
install:
    - yarn
    - yarn webdriver:update
script:
    - yarn lint
    - yarn pretty
    - yarn build:testapp
    - yarn test:ci
    - yarn test:async:node8
    - yarn readme:validate
